input {
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message"
  }

  if "_jsonparsefailure" not in [tags] {
    # Validasi field wajib: level, service, player_id, player_name, event_type, linked_gate, status, message
    if ![level] or ![service] or ![player_id] or ![player_name] or ![event_type] or ![linked_gate] or ![status] or ![message] {
      mutate {
        add_tag => ["missing_required_fields"]
      }
    }

    # Jika event_type bernilai Invalid Gate Request, tambahkan tag suspicious_activity
    if [event_type] == "Invalid Gate Request" {
      mutate {
        add_tag => ["suspicious_activity"]
      }
    }

    # Jika event_type bernilai Challenge Failed, tambahkan tag challenge_failed
    if [event_type] == "Challenge Failed" {
      mutate {
        add_tag => ["challenge_failed"]
      }
    }
  }
}

output {
  # Log malformed JSON atau field wajib hilang -> index linked-verse-errors
  if "_jsonparsefailure" in [tags] or "missing_required_fields" in [tags] {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "linked-verse-errors-%{+YYYY.MM.dd}"
    }
  }
  # Log valid -> index linked-verse-logs
  else {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "linked-verse-logs-%{+YYYY.MM.dd}"
    }
  }
}
